import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const jakarta = localFont({
  src: [
    {
      path: "../assets/fonts/PlusJakartaSans-Bold.ttf",
      style: "bold",
    },
    {
      path: "../assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
    {
      path: "../assets/fonts/PlusJakartaSans-Medium.ttf",
      style: "medium",
    },
    {
      path: "../assets/fonts/PlusJakartaSans-VariableFont_wght.ttf",
      style: "medium",
    },
  ],
  variable: "--font-jakarta",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.className} md:bg-sky-100`}
      >
        <div className="w-full h-[100vh] flex items-center justify-center">
        {children}
        </div>
      </body>
    </html>
  );
}
